config/routes.rb
Rails.application.routes.draw do
  resources :audio_recording_fragments
  resources :audio_recordings
  resources :tags
  resources :agents
  resources :artefacts
  resources :milliseconds
  resources :seconds
  resources :minutes
  resources :hours
  resources :days
  resources :months
  resources :quarters
  resources :years
  resources :decades
  resources :absolute_date_nodes
  resources :geospatial_nodes
  resources :absolute_date_time_roots
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quarter.rb
class Quarter < AbsoluteDateNode
  include Neo4j::ActiveNode
  property :name, type: String
  property :quarter, type: Integer
  # 1, 2, 3, 4 = Q1, Q2, Q3, Q4

  property :normalized_name, type: String
  validates_presence_of :name
  validate :set_normalized_name

  private
  def set_normalized_name
    self.normalized_name = self.name.downcase if self.name
  end

  public
  has_one :out, :datetimeSemanticZoomOut, type: :DATETIME_SEMANTIC_ZOOM_OUT, model_class: :Year, unique: true
  has_many :in, :datetimeSemanticZoomIn, type: :DATETIME_SEMANTIC_ZOOM_IN, model_class: :Month

end

app/controllers/quarters_controller.rb
class QuartersController < ApplicationController
  before_action :set_quarter, only: [:show, :edit, :update, :destroy]

  # GET /quarters
  def index
    @quarters = Quarter.all
  end

  # GET /quarters/1
  def show
  end

  # GET /quarters/new
  def new
    @quarter = Quarter.new
  end

  # GET /quarters/1/edit
  def edit
  end

  # POST /quarters
  def create
    @quarter = Quarter.new(quarter_params)

    if @quarter.save
      redirect_to @quarter, notice: 'Quarter was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /quarters/1
  def update
    if @quarter.update(quarter_params)
      redirect_to @quarter, notice: 'Quarter was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /quarters/1
  def destroy
    @quarter.destroy
    redirect_to quarters_url, notice: 'Quarter was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quarter
      @quarter = Quarter.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def quarter_params
                              
      params.require(:quarter).permit( :name, :quarter, :datetimeSemanticZoomOut => [], :datetimeSemanticZoomIn => [] )
    end
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/views/quarters/_form.html.erb
<div class="ui text container">
  <div class="ui form">
    <%= form_for(@quarter) do |f| %>
      <% if @quarter.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@quarter.errors.count, "error") %> prohibited this quarter from being saved:</h2>
          <ul>
            <% @quarter.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


            <div class="field">
              <%= f.label :name %><br>
              <%= f.text_field :name %>
            </div>
          
  

            <div class="field">
              <%= f.label :quarter %><br>
              <%= f.number_field :quarter %>
            </div>
          
  

         
            <div class="field">
              <%= f.label :datetimeSemanticZoomOut_id %><br>
              
              # Edit the Class.all.sort to the Class name of the connected node (such as `GeospatialNode.all.sort`)
              <%= f.collection_select(:datetimeSemanticZoomOut, Class.all.sort { |a,b| a.name <=> b.name }, :id, :name, options = {:prompt => "Please Select an Item", :selected => @quarter.datetimeSemanticZoomOut.map(&:id)}, html_options = {:multiple => true, :class=>"search"}) %>
            </div>

  

         
            <div class="field">
              <%= f.label :datetimeSemanticZoomIn_id %><br>
              
              # Edit the Class.all.sort to the Class name of the connected node (such as `GeospatialNode.all.sort`)
              <%= f.collection_select(:datetimeSemanticZoomIn, Class.all.sort { |a,b| a.name <=> b.name }, :id, :name, options = {:prompt => "Please Select an Item", :selected => @quarter.datetimeSemanticZoomIn.map(&:id)}, html_options = {:multiple => true, :class=>"search"}) %>
            </div>

  

      <div class="actions">
        <%= f.submit html_options = {:class=>"ui button"} %>
      </div>
    <% end %>
  </div>
</div>

<script>
$('.search')
  .dropdown()
;
</script>

app/views/quarters/edit.html.erb
<h1>Editing Quarter</h1>

<%= render 'form', quarter: @quarter %>

<%= link_to 'Show', @quarter %> |
<%= link_to 'Back', quarters_path %>

app/views/quarters/index.html.erb
<p id="notice"><%= notice %></p>

<div class="ui very padded container ">
  <h1>Quarters</h1>

  <table class="ui very basic celled table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Quarter</th>
        <th>Datetimesemanticzoomout</th>
        <th>Datetimesemanticzoomin</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @quarters.limit(45).each do |quarter| %>
        <tr>


          <td>
              <%= link_to quarter.name, quarter %>
          </td>

          <td>
            <%- if !quarter.quarter.nil? %>
              <%= quarter.quarter %>
            <%- end %>
          </td>

          <td>
            <%- if !quarter.datetimeSemanticZoomOut.empty? %>
              <%- quarter.datetimeSemanticZoomOut.each do |datetimeSemanticZoomOut| -%>
                <%= link_to datetimeSemanticZoomOut.name, datetimeSemanticZoomOut %>
              <%- end -%>
            <%- end -%>
          </td>

          <td>
            <%- if !quarter.datetimeSemanticZoomIn.empty? %>
              <%- quarter.datetimeSemanticZoomIn.each do |datetimeSemanticZoomIn| -%>
                <%= link_to datetimeSemanticZoomIn.name, datetimeSemanticZoomIn %>
              <%- end -%>
            <%- end -%>
          </td>
          <td><%= link_to 'Edit', edit_quarter_path(quarter) %></td>
          <td><%= link_to 'Destroy', quarter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Quarter', new_quarter_path %>
</div>

app/views/quarters/new.html.erb
<h1>New Quarter</h1>

<%= render 'form', quarter: @quarter %>

<%= link_to 'Back', quarters_path %>

app/views/quarters/show.html.erb
<p id="notice"><%= notice %></p>

<div class="ui">
  <a class="ui labeled icon button" href="<%= quarters_path %>">
    <i class="up arrow icon"></i>
    List Quarters
  </a>
  <a class="ui basic icon button" href="<%= edit_quarter_path(@quarter) %>">
    <i class="edit icon"></i>
    Edit
  </a>
</div>

<div class="ui hidden divider"></div>

<div class="ui vertical masthead center aligned segment">
  <h1 class="ui header">Quarter</h1>
</div>

<div class="ui text container">

  <p>
    <strong>Name:</strong>
    <%= @quarter.name -%>
  </p>

  <p>
    <strong>Quarter:</strong>
    <%= @quarter.quarter -%>
  </p>

  <p>
    <strong>Datetimesemanticzoomout:</strong>
    <% if !@quarter.datetimeSemanticZoomOut.nil? -%>
      <% @quarter.datetimeSemanticZoomOut.each do |datetimeSemanticZoomOut| -%>
        <%= link_to datetimeSemanticZoomOut.name, datetimeSemanticZoomOut %>
      <% end -%>
    <% end -%>
  </p>

  <p>
    <strong>Datetimesemanticzoomin:</strong>
    <% if !@quarter.datetimeSemanticZoomIn.nil? -%>
      <% @quarter.datetimeSemanticZoomIn.each do |datetimeSemanticZoomIn| -%>
        <%= link_to datetimeSemanticZoomIn.name, datetimeSemanticZoomIn %>
      <% end -%>
    <% end -%>
  </p>
</div>