config/routes.rb
Rails.application.routes.draw do
  resources :audio_recording_fragments
  resources :audio_recordings
  resources :tags
  resources :agents
  resources :artefacts
  resources :milliseconds
  resources :seconds
  resources :minutes
  resources :hours
  resources :days
  resources :months
  resources :quarters
  resources :years
  resources :decades
  resources :absolute_date_nodes
  resources :geospatial_nodes
  resources :absolute_date_time_roots
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/audio_recording.rb
class AudioRecording < Artefact
#  include Neo4j::ActiveNode
#  property :name, type: String
  property :md5AtSave, type: String
  property :waveformArray, type: String
  property :durationInSeconds, type: Float

  ## Sample
  # file = File.read('./some-file.json') #generated by `./audiowaveformLinux -i Stephanie\ -\ 2016-03-21\ -\ Office,\ Speakers\ \(Sticker\ shock\),\ meeting\ Kate\ in\ Person.mp3 --pixels-per-second 1 -b 8 -o some-file.json`
  # data_hash = JSON.parse(file)
  # rec = AudioRecording.first
  # rec.waveformArrayJSON = data_hash['data'].every_nth(5).collect { |n| n.to_f / 100 }
    # to_f forces it to be a float
    # / 100 scales it down. Wavesurfer expects -1..1
    # every_nth(5) is a monkey-patched function that returns every 5th element of the array, resulting in about 800 samples from 3600  

  has_neo4jrb_attached_file :ingestedFile
  validates_attachment_content_type :ingestedFile, content_type: /\Aaudio\/.*\Z/
  has_neo4jrb_attached_file :ingestedVisualizationFile
  validates_attachment_content_type :ingestedVisualizationFile, content_type: /\Aimage\/.*\Z/

  has_neo4jrb_attached_file :ingestedFileWaveformArrayJSON 
#  validates_attachment_content_type :ingestedFileWaveformArrayJSON, content_type: ["/\Atext\/.*\Z/", "application/json"]
  do_not_validate_attachment_file_type :ingestedFileWaveformArrayJSON

  ## Ideas for JSON generation:
  # 1. change all keys and hashes to lowercase
  # 2. Include more data, such as OS version

  has_many :in, :origionalArtefactFragments, type: :ORIGINAL_AUDIORECORDING, model_class: :AudioRecordingFragment

  ## Note: TIMEZONES
  # Ruby will automatically find the GMT offset if you use this format:
  # Time.zone = 'America/Halifax'
  # Time.zone.parse(String)
  # Note: Time.zone.parse("121028 215320") will return: 
    # "Sun, 28 Oct 0012 21:53:20 LMT -04:14" (0012, not 2012) aka -61762427536
    # When possible, use 4-digit dates

  def self.returnTrue
    return true
  end

  def returnTrue2
    return true
  end


  def getWaveSurferArray
    # Has to be called after the audio file has been saved through ingest
    # Find the duration of the file
      #self.durationInSeconds
    # arrive at 800 samples:
      if self.durationInSeconds >= 800
        pixelsPerSecond = 1
        skipAmount = (self.durationInSeconds / 800).ceil #ceil always rounds up
      elsif self.durationInSeconds.between?(100, 800)
        # Calculate pixels per second as 800 / duration
        pixelsPerSecond = (800 / self.durationInSeconds).ceil
        # No skip needed
        # skipAmount = nil #Already nil; not defined
      else 
        pixelsPerSecond = 4
      end
    puts "Audiowaveform start"
    puts `audiowaveform -i "#{File.absolute_path(self.ingestedFile.path)}" --pixels-per-second #{pixelsPerSecond} -b 8 -o "/tmp/#{File.basename(self.ingestedFile.path)}.json"`
    puts "Audiowaveform end"
    
    # save JSON to ingestedFileWaveformArrayJSON
    jsonTempFile = File.open("/tmp/#{File.basename(self.ingestedFile.path)}.json")
    puts "File.exist?(jsonTempFile): #{File.exist?(jsonTempFile)}"
    self.ingestedFileWaveformArrayJSON = jsonTempFile
    self.save
    
    # Parse tempfile.json
    data_hash = JSON.parse(Paperclip.io_adapters.for(self.ingestedFileWaveformArrayJSON).read)
    # Do more math to get to ~800 samples
    # Save the array of samples as self.waveformArray
    if skipAmount
      self.waveformArray = data_hash['data'].every_nth(skipAmount).collect { |n| n.to_f / 100 }
    else
      self.waveformArray = data_hash['data'].collect { |n| n.to_f / 100 }
    end
    self.save
    return true
  end


  def self.ingestUnparsedAudioRecording(origionalFilename, fullpath)
    puts "try to get the file that's passed"
    if !audioRecordingFile = File.open(fullpath)
      return false, "File could not be opened"
    end
#    audioRecordingFileMetadataTmp = File.open("/tmp/#{origionalFilename}.json")
    audioRecordingFileMetadata = {}
    audioRecordingFileMetadata['original'] = audioRecordingFile.getOSMetaDataObject
    audioRecordingFileMetadata['sox'] = `/usr/bin/sox --i "#{File.absolute_path(audioRecordingFile)}"`.split(/\n+/).each_with_object({}) { |s,h| key, value = s.scan(/([\w\s]+)\s+(.*)/).first; h[key.strip]=value.sub(/:/, ' ').strip if value}
    audioRecordingFileMetadata['durationInSeconds'] = `/usr/bin/sox --i -D "#{File.absolute_path(audioRecordingFile)}"`.strip.to_f
    
#    audioRecordingFileMetadataTmp = Tempfile.new([origionalFilename, ".json"])
    
#    audioRecordingFileMetadataTmp = File.new("#{origionalFilename}.json")
    File.open("/tmp/#{origionalFilename}.json", "w") {|f| f.write(JSON.pretty_generate(audioRecordingFileMetadata)) } #Automatically closes the file afterwards. The result is the number of bytes written, NOT the File object
#    audioRecordingFileMetadataTmp.close
#    metadataJSON.original_filename = "#{origionalFilename}.json"

#    puts metadataJSON
    puts "Calling sox"
    puts system "sox \"#{fullpath}\" -n spectrogram -r -o \"/tmp/#{origionalFilename}.png\""
    puts "Done calling sox?"
#    audioRecordingFileMetadataTmp.close
#    audioRecordingFileMetadataTmp << JSON.pretty_generate(audioRecordingFileMetadata)
#    audioRecordingFileMetadataTmp.rewind #Saves the file
   # puts audioRecordingFileMetadataTmp.read
    audioRecordingNode = AudioRecording.merge(name: origionalFilename)

    audioRecordingNode.ingestedFile = audioRecordingFile
    if audioRecordingFileMetadata['durationInSeconds']
      audioRecordingNode.durationInSeconds = audioRecordingFileMetadata['durationInSeconds']
    end
    audioRecordingNode.save
    audioRecordingFile.close

    if metadataFile = File.open("/tmp/#{origionalFilename}.json")
      audioRecordingNode.ingestedFileMetadata = metadataFile
#    audioRecordingNode.ingestedFileMetadata = audioRecordingFileMetadataTmp
      audioRecordingNode.save
      metadataFile.close
    else
      puts "Could not open '/tmp/#{origionalFilename}.json'"
    end

    visualizationFile = File.open("/tmp/#{origionalFilename}.png")
    audioRecordingNode.ingestedVisualizationFile = visualizationFile
    audioRecordingNode.save
    visualizationFile.close
    
#    audioRecordingNode.returnTrue2
#    audioRecordingNode.returnTrue
    audioRecordingNode.getWaveSurferArray

#    puts "audioRecordingNode.errors: #{audioRecordingNode.errors}"
#    puts "audioRecordingNode.errors.messages: #{audioRecordingNode.errors.messages}"
#    puts "audioRecordingNode.errors.inspect: #{audioRecordingNode.errors.inspect}"
#    puts audioRecordingNode.ingestedFileMetadata.errors.messages
#    puts audioRecordingNode.ingestedFileMetadata.errors.inspect
#    puts audioRecordingNode.save
#    audioRecordingFile.close
  end

  def self.ingestParsedAudioFolderOfRecordings()

    jsonIndex = File.join("**", "*.json")
    # puts jsonIndex ##jsonIndex was phased out. Now it's a json for each snippet and no index file

    Dir.glob(jsonIndex) {|file|
      # 'file' is the relative path and filename. As in 'soxflactemp.noconversion/index.json'
      puts file
      ingestParsedAudioRecording(file) #Sends index.json to the parsing function
      # Each index.json afterwards will be for different folders (hopefully)

      # puts jsonFile.absolute_path
      # if jsonFileParsed = JSON.parse(jsonFile)
      #     jsonFileParsed.each do |jsonFileParsedEntry|
      #         puts jsonFileParsedEntry['file']
      #         snippetJsonFile = File.read("#{jsonFileParsedEntry['file']}")
      #     end
      # end
    }

  end

end

class ITunesVoiceMemo < AudioRecording

end

app/controllers/audio_recordings_controller.rb
class AudioRecordingsController < ApplicationController
  before_action :set_audio_recording, only: [:show, :edit, :update, :destroy]

  # GET /audio_recordings
  def index
    @audio_recordings = AudioRecording.all
  end

  # GET /audio_recordings/1
  def show
  end

  # GET /audio_recordings/new
  def new
    @audio_recording = AudioRecording.new
  end

  # GET /audio_recordings/1/edit
  def edit
  end

  # POST /audio_recordings
  def create
    @audio_recording = AudioRecording.new(audio_recording_params)

    if @audio_recording.save
      redirect_to @audio_recording, notice: 'Audio recording was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /audio_recordings/1
  def update
    if @audio_recording.update(audio_recording_params)
      redirect_to @audio_recording, notice: 'Audio recording was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /audio_recordings/1
  def destroy
    @audio_recording.destroy
    redirect_to audio_recordings_url, notice: 'Audio recording was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audio_recording
      @audio_recording = AudioRecording.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def audio_recording_params
                              
      params.require(:audio_recording).permit( :name, :md5AtSave, :waveformArray, :durationInSeconds, :origionalArtefactFragments => [] )
    end
end

app/helpers/audio_recordings_helper.rb
module AudioRecordingsHelper
end

app/views/audio_recordings/_form.html.erb
<div class="ui text container">
  <div class="ui form">
    <%= form_for(@audio_recording) do |f| %>
      <% if @audio_recording.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@audio_recording.errors.count, "error") %> prohibited this audio_recording from being saved:</h2>
          <ul>
            <% @audio_recording.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


            <div class="field">
              <%= f.label :name %><br>
              <%= f.text_field :name %>
            </div>
          
  

            <div class="field">
              <%= f.label :md5AtSave %><br>
              <%= f.text_field :md5AtSave %>
            </div>
          
  

            <div class="field">
              <%= f.label :waveformArray %><br>
              <%= f.text_field :waveformArray %>
            </div>
          
  

            <div class="field">
              <%= f.label :durationInSeconds %><br>
              <%= f.number_field :durationInSeconds %>
            </div>
          
  

         
            <div class="field">
              <%= f.label :origionalArtefactFragments_id %><br>
              
              # Edit the Class.all.sort to the Class name of the connected node (such as `GeospatialNode.all.sort`)
              <%= f.collection_select(:origionalArtefactFragments, Class.all.sort { |a,b| a.name <=> b.name }, :id, :name, options = {:prompt => "Please Select an Item", :selected => @audio_recording.origionalArtefactFragments.map(&:id)}, html_options = {:multiple => true, :class=>"search"}) %>
            </div>

  

      <div class="actions">
        <%= f.submit html_options = {:class=>"ui button"} %>
      </div>
    <% end %>
  </div>
</div>

<script>
$('.search')
  .dropdown()
;
</script>

app/views/audio_recordings/edit.html.erb
<h1>Editing Audio Recording</h1>

<%= render 'form', audio_recording: @audio_recording %>

<%= link_to 'Show', @audio_recording %> |
<%= link_to 'Back', audio_recordings_path %>

app/views/audio_recordings/index.html.erb
<p id="notice"><%= notice %></p>

<div class="ui very padded container ">
  <h1>Audio Recordings</h1>

  <table class="ui very basic celled table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Md5atsave</th>
        <th>Waveformarray</th>
        <th>Durationinseconds</th>
        <th>Origionalartefactfragments</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @audio_recordings.limit(45).each do |audio_recording| %>
        <tr>


          <td>
              <%= link_to audio_recording.name, audio_recording %>
          </td>

          <td>
            <%- if !audio_recording.md5AtSave.nil? %>
              <%= audio_recording.md5AtSave %>
            <%- end %>
          </td>

          <td>
            <%- if !audio_recording.waveformArray.nil? %>
              <%= audio_recording.waveformArray %>
            <%- end %>
          </td>

          <td>
            <%- if !audio_recording.durationInSeconds.nil? %>
              <%= audio_recording.durationInSeconds %>
            <%- end %>
          </td>

          <td>
            <%- if !audio_recording.origionalArtefactFragments.empty? %>
              <%- audio_recording.origionalArtefactFragments.each do |origionalArtefactFragments| -%>
                <%= link_to origionalArtefactFragments.name, origionalArtefactFragments %>
              <%- end -%>
            <%- end -%>
          </td>
          <td><%= link_to 'Edit', edit_audio_recording_path(audio_recording) %></td>
          <td><%= link_to 'Destroy', audio_recording, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Audio Recording', new_audio_recording_path %>
</div>

app/views/audio_recordings/new.html.erb
<h1>New Audio Recording</h1>

<%= render 'form', audio_recording: @audio_recording %>

<%= link_to 'Back', audio_recordings_path %>

app/views/audio_recordings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="ui">
  <a class="ui labeled icon button" href="<%= audio_recordings_path %>">
    <i class="up arrow icon"></i>
    List Audio Recordings
  </a>
  <a class="ui basic icon button" href="<%= edit_audio_recording_path(@audio_recording) %>">
    <i class="edit icon"></i>
    Edit
  </a>
</div>

<div class="ui hidden divider"></div>

<div class="ui vertical masthead center aligned segment">
  <h1 class="ui header">Audio Recording</h1>
</div>

<div class="ui text container">

  <p>
    <strong>Name:</strong>
    <%= @audio_recording.name -%>
  </p>

  <p>
    <strong>Md5atsave:</strong>
    <%= @audio_recording.md5AtSave -%>
  </p>

  <p>
    <strong>Waveformarray:</strong>
    <%= @audio_recording.waveformArray -%>
  </p>

  <p>
    <strong>Durationinseconds:</strong>
    <%= @audio_recording.durationInSeconds -%>
  </p>

  <p>
    <strong>Origionalartefactfragments:</strong>
    <% if !@audio_recording.origionalArtefactFragments.nil? -%>
      <% @audio_recording.origionalArtefactFragments.each do |origionalArtefactFragments| -%>
        <%= link_to origionalArtefactFragments.name, origionalArtefactFragments %>
      <% end -%>
    <% end -%>
  </p>
</div>