config/routes.rb
Rails.application.routes.draw do
  resources :audio_recording_fragments
  resources :audio_recordings
  resources :tags
  resources :agents
  resources :artefacts
  resources :milliseconds
  resources :seconds
  resources :minutes
  resources :hours
  resources :days
  resources :months
  resources :quarters
  resources :years
  resources :decades
  resources :absolute_date_nodes
  resources :geospatial_nodes
  resources :absolute_date_time_roots
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/day.rb
class Day < AbsoluteDateNode
  include Neo4j::ActiveNode
  property :name, type: String
  property :day, type: String


  property :normalized_name, type: String
  validates_presence_of :name
  validate :set_normalized_name

  private
  def set_normalized_name
    self.normalized_name = self.name.downcase if self.name
  end

  public
  has_one :out, :datetimeSemanticZoomOut, type: :DATETIME_SEMANTIC_ZOOM_OUT, model_class: :Month, unique: true
  has_many :in, :datetimeSemanticZoomIn, type: :DATETIME_SEMANTIC_ZOOM_OUT, model_class: :Hour

end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  # GET /days
  def index
    @days = Day.all
  end

  # GET /days/1
  def show
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  def create
    @day = Day.new(day_params)

    if @day.save
      redirect_to @day, notice: 'Day was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /days/1
  def update
    if @day.update(day_params)
      redirect_to @day, notice: 'Day was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /days/1
  def destroy
    @day.destroy
    redirect_to days_url, notice: 'Day was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def day_params
                              
      params.require(:day).permit( :name, :day, :datetimeSemanticZoomOut => [], :datetimeSemanticZoomIn => [] )
    end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.erb
<div class="ui text container">
  <div class="ui form">
    <%= form_for(@day) do |f| %>
      <% if @day.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>
          <ul>
            <% @day.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


            <div class="field">
              <%= f.label :name %><br>
              <%= f.text_field :name %>
            </div>
          
  

            <div class="field">
              <%= f.label :day %><br>
              <%= f.text_field :day %>
            </div>
          
  

         
            <div class="field">
              <%= f.label :datetimeSemanticZoomOut_id %><br>
              
              # Edit the Class.all.sort to the Class name of the connected node (such as `GeospatialNode.all.sort`)
              <%= f.collection_select(:datetimeSemanticZoomOut, Class.all.sort { |a,b| a.name <=> b.name }, :id, :name, options = {:prompt => "Please Select an Item", :selected => @day.datetimeSemanticZoomOut.map(&:id)}, html_options = {:multiple => true, :class=>"search"}) %>
            </div>

  

         
            <div class="field">
              <%= f.label :datetimeSemanticZoomIn_id %><br>
              
              # Edit the Class.all.sort to the Class name of the connected node (such as `GeospatialNode.all.sort`)
              <%= f.collection_select(:datetimeSemanticZoomIn, Class.all.sort { |a,b| a.name <=> b.name }, :id, :name, options = {:prompt => "Please Select an Item", :selected => @day.datetimeSemanticZoomIn.map(&:id)}, html_options = {:multiple => true, :class=>"search"}) %>
            </div>

  

      <div class="actions">
        <%= f.submit html_options = {:class=>"ui button"} %>
      </div>
    <% end %>
  </div>
</div>

<script>
$('.search')
  .dropdown()
;
</script>

app/views/days/edit.html.erb
<h1>Editing Day</h1>

<%= render 'form', day: @day %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<p id="notice"><%= notice %></p>

<div class="ui very padded container ">
  <h1>Days</h1>

  <table class="ui very basic celled table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Day</th>
        <th>Datetimesemanticzoomout</th>
        <th>Datetimesemanticzoomin</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @days.limit(45).each do |day| %>
        <tr>


          <td>
              <%= link_to day.name, day %>
          </td>

          <td>
            <%- if !day.day.nil? %>
              <%= day.day %>
            <%- end %>
          </td>

          <td>
            <%- if !day.datetimeSemanticZoomOut.empty? %>
              <%- day.datetimeSemanticZoomOut.each do |datetimeSemanticZoomOut| -%>
                <%= link_to datetimeSemanticZoomOut.name, datetimeSemanticZoomOut %>
              <%- end -%>
            <%- end -%>
          </td>

          <td>
            <%- if !day.datetimeSemanticZoomIn.empty? %>
              <%- day.datetimeSemanticZoomIn.each do |datetimeSemanticZoomIn| -%>
                <%= link_to datetimeSemanticZoomIn.name, datetimeSemanticZoomIn %>
              <%- end -%>
            <%- end -%>
          </td>
          <td><%= link_to 'Edit', edit_day_path(day) %></td>
          <td><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Day', new_day_path %>
</div>

app/views/days/new.html.erb
<h1>New Day</h1>

<%= render 'form', day: @day %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<div class="ui">
  <a class="ui labeled icon button" href="<%= days_path %>">
    <i class="up arrow icon"></i>
    List Days
  </a>
  <a class="ui basic icon button" href="<%= edit_day_path(@day) %>">
    <i class="edit icon"></i>
    Edit
  </a>
</div>

<div class="ui hidden divider"></div>

<div class="ui vertical masthead center aligned segment">
  <h1 class="ui header">Day</h1>
</div>

<div class="ui text container">

  <p>
    <strong>Name:</strong>
    <%= @day.name -%>
  </p>

  <p>
    <strong>Day:</strong>
    <%= @day.day -%>
  </p>

  <p>
    <strong>Datetimesemanticzoomout:</strong>
    <% if !@day.datetimeSemanticZoomOut.nil? -%>
      <% @day.datetimeSemanticZoomOut.each do |datetimeSemanticZoomOut| -%>
        <%= link_to datetimeSemanticZoomOut.name, datetimeSemanticZoomOut %>
      <% end -%>
    <% end -%>
  </p>

  <p>
    <strong>Datetimesemanticzoomin:</strong>
    <% if !@day.datetimeSemanticZoomIn.nil? -%>
      <% @day.datetimeSemanticZoomIn.each do |datetimeSemanticZoomIn| -%>
        <%= link_to datetimeSemanticZoomIn.name, datetimeSemanticZoomIn %>
      <% end -%>
    <% end -%>
  </p>
</div>