config/routes.rb
Rails.application.routes.draw do
  resources :audio_recording_fragments
  resources :audio_recordings
  resources :tags
  resources :agents
  resources :artefacts
  resources :milliseconds
  resources :seconds
  resources :minutes
  resources :hours
  resources :days
  resources :months
  resources :quarters
  resources :years
  resources :decades
  resources :absolute_date_nodes
  resources :geospatial_nodes
  resources :absolute_date_time_roots
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag 
  include Neo4j::ActiveNode
  property :name, type: String

  id_property :uuid, auto: :uuid

  property :updated_at
  property :created_at


  property :normalized_name, type: String
  validates_presence_of :name
  validate :set_normalized_name

  private
  def set_normalized_name
    self.normalized_name = self.name.downcase if self.name
  end

  public
  has_many :in, :tagged, type: :CONCEPTUAL_TAG, model_class: :Artefact
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to @tag, notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to @tag, notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_to tags_url, notice: 'Tag was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tag_params
                              
      params.require(:tag).permit( :name, :tagged => [] )
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<div class="ui text container">
  <div class="ui form">
    <%= form_for(@tag) do |f| %>
      <% if @tag.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>
          <ul>
            <% @tag.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


            <div class="field">
              <%= f.label :name %><br>
              <%= f.text_field :name %>
            </div>
          
  

         
            <div class="field">
              <%= f.label :tagged_id %><br>
              
              <%= f.collection_select(:tagged, Artefact.all.sort { |a,b| a.name <=> b.name }, :id, :name, options = {:prompt => "Please Select an Item", :selected => @tag.tagged.map(&:id)}, html_options = {:multiple => true, :class=>"search"}) %>
            </div>

  

      <div class="actions">
        <%= f.submit html_options = {:class=>"ui button"} %>
      </div>
    <% end %>
  </div>
</div>

<script>
$('.search')
  .dropdown()
;
</script>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<div class="ui very padded container ">
  <h1>Tags</h1>

  <table class="ui very basic celled table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Tagged</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @tags.limit(45).each do |tag| %>
        <tr>


          <td>
              <%= link_to tag.name, tag %>
          </td>

          <td>
            <%- if !tag.tagged.empty? %>
              <%- tag.tagged.each do |tagged| -%>
                <%= link_to tagged.name, tagged %>
              <%- end -%>
            <%- end -%>
          </td>
          <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
          <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Tag', new_tag_path %>
</div>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<div class="ui">
  <a class="ui labeled icon button" href="<%= tags_path %>">
    <i class="up arrow icon"></i>
    List Tags
  </a>
  <a class="ui basic icon button" href="<%= edit_tag_path(@tag) %>">
    <i class="edit icon"></i>
    Edit
  </a>
</div>

<div class="ui hidden divider"></div>

<div class="ui vertical masthead center aligned segment">
  <h1 class="ui header">Tag</h1>
</div>

<div class="ui text container">

  <p>
    <strong>Name:</strong>
    <%= @tag.name -%>
  </p>

  <p>
    <strong>Tagged:</strong>
    <% if !@tag.tagged.nil? -%>
      <% @tag.tagged.each do |tagged| -%>
        <%= link_to tagged.name, tagged %>
      <% end -%>
    <% end -%>
  </p>
</div>